// Package main: a Go consumer generated from the COMMITTED OpenAPI snapshot.
//
// WHAT THIS DEMONSTRATES: the break arrives at COMPILE TIME. Change
// `total: int` to `total: str` in the provider, regenerate these types from the
// new snapshot, and `go build ./...` fails naming the field. That is the
// cheapest contract enforcement in existence and it needs no broker at all.
//
// WHAT TO LOOK FOR: it only catches breaks that change the SHAPE the generator
// saw. Making a required response field optional does not change any Go type --
// `Total int` still compiles, still parses, and silently reads 0 for an absent
// field. That gap is the entire argument for consumer-driven contracts.
//
// Generated by hand here rather than by oapi-codegen so the file is readable and
// the lab has no code-generation step to break. Regenerate with:
//
//	go run ./cmd/gen -schema ../api/openapi.snapshot.json     (not shipped: see topic 6)
//	oapi-codegen -generate types -package main ../api/openapi.snapshot.json
package main

// CustomerOrderOut mirrors components.schemas.CustomerOrderOut.
type CustomerOrderOut struct {
	ID         int64  `json:"id"`
	Status     string `json:"status"`
	TotalCents int64  `json:"total_cents"`
}

// CustomerOrderListOut mirrors components.schemas.CustomerOrderListOut.
type CustomerOrderListOut struct {
	Items []CustomerOrderOut `json:"items"`
	// THE FIELD topic 6's first break changes. `int64` here versus `string` in
	// the provider is a compile error the moment these types are regenerated --
	// which is the point, and which is also why the regeneration step has to be
	// in CI rather than in someone's shell history.
	Total int64 `json:"total"`
}

// ApiError mirrors components.schemas.ApiError. Declared because the snapshot
// declares 404 and 503 response bodies; an error the caller is supposed to
// handle but which has no type here is one the caller cannot handle.
type ApiError struct {
	Error   string `json:"error"`
	Message string `json:"message"`
}
