// Layer 10 lab - open-model load against the `gateway`. Topic 2.
//
// What this demonstrates
//     The knee. Latency against arrival rate, generated by an OPEN-model
//     executor: requests are issued on a clock, whether or not previous
//     ones have come back. A closed-loop generator (`constant-vus`, or any
//     "N threads each looping") cannot reproduce topic 2's failure at all,
//     because when the server slows the generator slows with it -- feedback
//     that no real caller provides. That is coordinated omission, and it
//     deletes the worst part of the incident from the histogram.
//
// What to look for
//     - TTFT p50 and p99 as RATE rises across runs, TAKEN FROM THE GATEWAY,
//       not from k6. This script prints both and they are not the same
//       number: see the note below.
//       Flat p99 while RATE rises is not a good result, it is a broken
//       experiment: check the executor and check dropped_iterations.
//     - dropped_iterations at the end of the run. NON-ZERO MEANS THE
//       GENERATOR SATURATED, not the server, and every latency number in
//       that row is invalid. k6 prints it in the summary; the threshold
//       below turns it into a failed run so it cannot be missed.
//     - http_req_failed. Shed load never appears in a latency histogram,
//       so p99 improves every time the system gets worse. Read both.
//
// Run (RATE is the only variable; step it across runs, do not ramp inside
// one run -- you want a clean λ per row of the table):
//     docker compose run --rm k6 run /scripts/arrival_rate.js -e RATE=2
//     docker compose run --rm k6 run /scripts/arrival_rate.js -e RATE=4
//     docker compose run --rm k6 run /scripts/arrival_rate.js -e RATE=8

import http from 'k6/http';
import { Trend, Counter } from 'k6/metrics';

const RATE = Number(__ENV.RATE || 2);
const DURATION = __ENV.DURATION || '60s';
const MAX_TOKENS = Number(__ENV.MAX_TOKENS || 128);
const GATEWAY_URL = __ENV.GATEWAY_URL || 'http://gateway:8000';

// NOT TTFT, and this is the trap. k6's http_req_waiting is time to the
// first response BYTE, and an ASGI StreamingResponse flushes the response
// HEADER before it pulls the first item out of the body generator. So this
// number is the time to the header -- a couple of milliseconds -- and it
// stays flat no matter how deep the queue behind it gets. Measured here:
// 2.8 ms at λ=4 and 2.9 ms at λ=16 while the gateway's own TTFT histogram
// went from 11 ms to 6.6 s over the same two runs.
//
// The honest TTFT is server-side, from the moment the gateway's upstream
// request is issued to the first byte of the first token, which is what
// gateway_ttft_seconds observes. setup()/teardown() below read it off
// /metrics and print it next to this one, so the two cannot be confused.
const firstByte = new Trend('first_byte', true);
const total = new Trend('response_total', true);
const errors = new Counter('gateway_errors');

export const options = {
  scenarios: {
    open: {
      // The one line this whole file exists to get right.
      executor: 'constant-arrival-rate',
      rate: RATE,
      timeUnit: '1s',
      duration: DURATION,
      // Pre-allocate generously: these VUs are not a concurrency limit,
      // they are the pool the executor draws from to keep issuing on
      // schedule. Too few and k6 throttles itself, which shows up as
      // dropped_iterations and invalidates the run.
      preAllocatedVUs: Math.max(50, RATE * 20),
      maxVUs: Math.max(200, RATE * 60),
    },
  },
  thresholds: {
    // A failed threshold here means the GENERATOR could not keep up. The
    // run is void; lower RATE or raise maxVUs and run it again.
    dropped_iterations: ['count == 0'],
  },
  discardResponseBodies: false,
  summaryTrendStats: ['avg', 'min', 'med', 'p(90)', 'p(95)', 'p(99)', 'max'],
};

export default function () {
  const res = http.post(
    `${GATEWAY_URL}/generate`,
    JSON.stringify({ user_message: 'How do I roll back a bad deploy?', max_tokens: MAX_TOKENS }),
    { headers: { 'Content-Type': 'application/json' }, timeout: '300s' },
  );

  firstByte.add(res.timings.waiting);
  total.add(res.timings.duration);
  if (res.status !== 200) {
    errors.add(1);
  }
}

export function handleSummary(data) {
  const dropped = (data.metrics.dropped_iterations || { values: { count: 0 } }).values.count;
  // handleSummary REPLACES k6's default summary, so anything not printed
  // here is lost.
  const t = data.metrics.first_byte.values;
  const r = data.metrics.response_total.values;
  const errs = (data.metrics.gateway_errors || { values: { count: 0 } }).values.count;
  const lines = [
    '',
    `λ = ${RATE} req/s for ${DURATION} against ${GATEWAY_URL}`,
    `first byte      p50 ${t.med.toFixed(1)} ms  p99 ${t['p(99)'].toFixed(1)} ms  ` +
      `<-- the HEADER, not the first token`,
    `response total  p50 ${r.med.toFixed(1)} ms  p99 ${r['p(99)'].toFixed(1)} ms`,
    `non-200 responses = ${errs}`,
    `dropped_iterations = ${dropped}` +
      (dropped > 0
        ? '   <-- GENERATOR SATURATED. This row is invalid; do not record it.'
        : '   (0 = the generator kept its schedule, so the latencies are real)'),
    '',
    'Record ttft p50/p99 next to the engine-side numbers from',
    '  curl -s localhost:8081/metrics | grep -E \'num_requests|preemption|prefix_cache\'',
    'A latency table without the queue depth beside it is the dashboard',
    'that lies, in table form.',
    '',
  ];
  return {
    stdout: lines.join('\n'),
    [`/out/arrival_rate-rate${RATE}.json`]: JSON.stringify(data, null, 2),
  };
}

// --- server-side TTFT -------------------------------------------------
// A Prometheus histogram is cumulative, so the run's own TTFT is the
// DIFFERENCE between the buckets before and after. Snapshot in setup(),
// read again in teardown(); both may issue HTTP, the default function's
// scope may not.

function ttftBuckets() {
  const res = http.get(`${GATEWAY_URL}/metrics`);
  const out = {};
  for (const line of String(res.body).split('\n')) {
    const m = line.match(/^gateway_ttft_seconds_bucket\{le="([^"]+)"\}\s+(\S+)/);
    if (m) out[m[1]] = Number(m[2]);
  }
  return out;
}

function quantile(delta, p) {
  const les = Object.keys(delta).sort((a, b) => Number(a) - Number(b));
  const total = delta[les[les.length - 1]];
  if (!total) return null;
  const target = p * total;
  let prevLe = 0;
  let prevC = 0;
  for (const le of les) {
    const c = delta[le];
    if (c >= target) {
      if (le === '+Inf') return prevLe;
      if (c === prevC) return Number(le);
      return prevLe + (Number(le) - prevLe) * ((target - prevC) / (c - prevC));
    }
    prevLe = Number(le);
    prevC = c;
  }
  return null;
}

export function setup() {
  return { before: ttftBuckets() };
}

export function teardown(data) {
  const after = ttftBuckets();
  const delta = {};
  for (const le of Object.keys(after)) delta[le] = after[le] - (data.before[le] || 0);
  const n = delta['+Inf'];
  if (!n) {
    console.log('gateway_ttft_seconds: no samples - is /metrics reachable?');
    return;
  }
  const f = (x) => (x === null ? 'n/a' : `${(x * 1000).toFixed(0)} ms`);
  console.log(
    `gateway_ttft_seconds (SERVER SIDE, n=${n}): ` +
      `p50 ${f(quantile(delta, 0.5))}  p90 ${f(quantile(delta, 0.9))}  ` +
      `p99 ${f(quantile(delta, 0.99))}   <-- this is the TTFT to record`,
  );
}
