"""
Layer 5 lab - reading k6's CSV output, and drawing it in a terminal.

WHAT THIS IS
  The shared half of the five plotters next to it. k6's `--out csv=` format is
  one row per SAMPLE - not per request, and not pre-aggregated - which is
  exactly what this layer needs: percentiles have to be computed from the
  samples that survived to here, never averaged from someone else's summary.

WHY ASCII FIRST
  Every plotter here prints a chart made of text and needs nothing installed.
  If matplotlib happens to be importable it also writes a PNG next to the CSV,
  but the terminal output is the primary artefact - a plotting script that
  cannot run without a dependency you have to install is a plotting script
  that does not get run.

THE FORMAT
  k6 writes a header row and then one row per sample:

    metric_name,timestamp,metric_value,check,error,error_code,expected_response,
    group,method,name,proto,scenario,service,status,subproto,tls_version,url,
    extra_tags,metadata

  Columns are located BY NAME rather than by position, because k6 has added
  columns between versions and will again. Custom tags arrive in `extra_tags`
  as `k=v&k2=v2`. Lines beginning with `#` are skipped, which is how the
  synthetic fixtures in ../out/fixtures/ label themselves.
"""
from __future__ import annotations

import csv
import gzip
import math
import os
import sys
from dataclasses import dataclass, field
from typing import Iterable, Iterator, Sequence

# Columns k6 emits as first-class fields that are worth treating as tags.
TAG_COLUMNS = ("check", "error_code", "expected_response", "group", "method",
               "name", "proto", "scenario", "service", "status", "url")


@dataclass
class Sample:
    metric: str
    t: float                      # unix seconds
    value: float
    tags: dict = field(default_factory=dict)

    def tag(self, name: str, default: str = "") -> str:
        return self.tags.get(name, default)


SYNTHETIC_WARNING = (
    "\n*** SYNTHETIC INPUT ***\n"
    "This file was generated by tools/make_fixtures.py from a model. It exists to\n"
    "prove the plotter runs, and for nothing else. Every number below is arithmetic\n"
    "this repository performed on itself - none of it was measured, and none of it\n"
    "belongs in a results table.\n"
)


def is_synthetic(path: str) -> bool:
    """True if the file labels itself synthetic in its first few lines."""
    try:
        with _open(path) as handle:
            for _ in range(4):
                line = handle.readline()
                if not line:
                    break
                if line.startswith("#") and "SYNTHETIC" in line.upper():
                    return True
    except OSError:
        return False
    return False


def _open(path: str):
    if path.endswith(".gz"):
        return gzip.open(path, "rt", newline="")
    return open(path, "rt", newline="")


def read_samples(path: str) -> Iterator[Sample]:
    """Stream one Sample per row. Tolerant of extra/missing/reordered columns."""
    with _open(path) as handle:
        rows = (line for line in handle if not line.lstrip().startswith("#"))
        reader = csv.DictReader(rows)
        if reader.fieldnames is None:
            return
        has = set(reader.fieldnames)
        for row in reader:
            name = row.get("metric_name")
            if not name:
                continue
            try:
                t = float(row.get("timestamp") or 0.0)
                value = float(row.get("metric_value") or 0.0)
            except ValueError:
                continue
            tags = {}
            for column in TAG_COLUMNS:
                if column in has:
                    raw = row.get(column) or ""
                    if raw != "":
                        tags[column] = raw
            extra = row.get("extra_tags") or ""
            for pair in extra.split("&"):
                if "=" in pair:
                    key, _, value_str = pair.partition("=")
                    if key:
                        tags[key] = value_str
            yield Sample(name, t, value, tags)


def load(path: str) -> list[Sample]:
    """Read a whole file, with a clear error rather than a traceback."""
    if not os.path.exists(path):
        raise SystemExit(
            f"no such file: {path}\n"
            f"Produce it with a k6 run, or plot the synthetic fixture instead:\n"
            f"  python3 tools/make_fixtures.py && "
            f"python3 {os.path.basename(sys.argv[0])} out/fixtures/{os.path.basename(path)}"
        )
    samples = list(read_samples(path))
    if not samples:
        raise SystemExit(f"{path} parsed to zero samples - is it a k6 --out csv= file?")
    return samples


def find_csvs(directory: str, prefix: str) -> list[str]:
    """Every CSV in `directory` whose basename starts with `prefix`, sorted."""
    if not os.path.isdir(directory):
        raise SystemExit(f"not a directory: {directory}")
    names = [n for n in sorted(os.listdir(directory))
             if n.startswith(prefix) and (n.endswith(".csv") or n.endswith(".csv.gz"))]
    if not names:
        raise SystemExit(
            f"no {prefix}*.csv in {directory}\n"
            f"Run the k6 scripts with --out csv=/out/{prefix}<variant>.csv first, or try\n"
            f"  python3 tools/make_fixtures.py && python3 {os.path.basename(sys.argv[0])} out/fixtures/"
        )
    return [os.path.join(directory, n) for n in names]


# ------------------------------------------------------------------ statistics

def percentile(values: Sequence[float], q: float) -> float:
    """Nearest-rank percentile. No interpolation: with a heavy tail the
    interpolated value is a number that no request ever experienced."""
    if not values:
        return float("nan")
    ordered = sorted(values)
    index = max(0, min(len(ordered) - 1, int(math.ceil(q / 100.0 * len(ordered))) - 1))
    return ordered[index]


def group_by(samples: Iterable[Sample], tag: str) -> dict[str, list[Sample]]:
    out: dict[str, list[Sample]] = {}
    for sample in samples:
        out.setdefault(sample.tag(tag), []).append(sample)
    return out


def values_of(samples: Iterable[Sample], metric: str, **tag_filters) -> list[float]:
    out = []
    for sample in samples:
        if sample.metric != metric:
            continue
        if any(sample.tag(k) != v for k, v in tag_filters.items()):
            continue
        out.append(sample.value)
    return out


def timespan(samples: Sequence[Sample]) -> float:
    if len(samples) < 2:
        return 0.0
    times = [s.t for s in samples]
    return max(times) - min(times)


def rate_of(samples: Sequence[Sample], metric: str, **tag_filters) -> float:
    """Samples per second of a metric within its own observed window.

    Used for achieved throughput: k6 emits one http_req_duration sample per
    request, so counting them over the window they span IS the achieved rate.
    """
    selected = [s for s in samples
                if s.metric == metric and all(s.tag(k) == v for k, v in tag_filters.items())]
    window = timespan(selected)
    if window <= 0:
        return float("nan")
    return len(selected) / window


def bucket_by_time(samples: Iterable[Sample], metric: str, width_s: float,
                   t0: float | None = None, **tag_filters) -> list[tuple[float, list[float]]]:
    """[(seconds_since_start, [values]), ...] in fixed-width buckets."""
    selected = [s for s in samples
                if s.metric == metric and all(s.tag(k) == v for k, v in tag_filters.items())]
    if not selected:
        return []
    start = t0 if t0 is not None else min(s.t for s in selected)
    buckets: dict[int, list[float]] = {}
    for sample in selected:
        index = int((sample.t - start) // width_s)
        buckets.setdefault(index, []).append(sample.value)
    return [(index * width_s, buckets[index]) for index in sorted(buckets)]


def run_start(samples: Iterable[Sample]) -> float:
    return min(s.t for s in samples)


# ---------------------------------------------------------------- ascii charts

BLOCKS = " ▁▂▃▄▅▆▇█"


def sparkline(values: Sequence[float]) -> str:
    finite = [v for v in values if math.isfinite(v)]
    if not finite:
        return ""
    low, high = min(finite), max(finite)
    span = (high - low) or 1.0
    out = []
    for v in values:
        if not math.isfinite(v):
            out.append(" ")
            continue
        index = int((v - low) / span * (len(BLOCKS) - 1))
        out.append(BLOCKS[max(0, min(len(BLOCKS) - 1, index))])
    return "".join(out)


def xy_plot(series: dict[str, Sequence[tuple[float, float]]], *, width: int = 78,
            height: int = 18, xlabel: str = "x", ylabel: str = "y",
            ymax: float | None = None, logy: bool = False) -> str:
    """A line chart made of characters. One glyph per series, legend below.

    Deliberately crude, and deliberately always available: the shape is the
    finding in this layer, and a shape you can see in a terminal on the
    machine that produced it beats a PNG you have to install something for.
    """
    glyphs = "o*+x#@%~"
    points = [(name, [(x, y) for x, y in pts if math.isfinite(y)])
              for name, pts in series.items()]
    points = [(n, p) for n, p in points if p]
    if not points:
        return "(no data to plot)\n"

    xs = [x for _, pts in points for x, _ in pts]
    ys = [y for _, pts in points for _, y in pts]
    xlo, xhi = min(xs), max(xs)
    ylo, yhi = 0.0, (ymax if ymax is not None else max(ys))
    if logy:
        ylo = max(1e-9, min(y for y in ys if y > 0) if any(y > 0 for y in ys) else 1e-9)
        yhi = max(yhi, ylo * 10)
    if yhi <= ylo:
        yhi = ylo + 1.0
    xspan = (xhi - xlo) or 1.0

    def yrow(value: float) -> int:
        if logy:
            value = max(value, ylo)
            frac = (math.log10(value) - math.log10(ylo)) / (math.log10(yhi) - math.log10(ylo))
        else:
            frac = (value - ylo) / (yhi - ylo)
        return height - 1 - max(0, min(height - 1, int(round(frac * (height - 1)))))

    grid = [[" "] * width for _ in range(height)]
    for index, (_name, pts) in enumerate(points):
        glyph = glyphs[index % len(glyphs)]
        for x, y in pts:
            column = max(0, min(width - 1, int(round((x - xlo) / xspan * (width - 1)))))
            grid[yrow(y)][column] = glyph

    label_width = 10
    lines = []
    for row in range(height):
        if logy:
            value = 10 ** (math.log10(ylo) + (height - 1 - row) / (height - 1) *
                           (math.log10(yhi) - math.log10(ylo)))
        else:
            value = ylo + (height - 1 - row) / (height - 1) * (yhi - ylo)
        lines.append(f"{value:>{label_width}.4g} |" + "".join(grid[row]))
    lines.append(" " * label_width + " +" + "-" * width)
    lines.append(" " * (label_width + 2) + f"{xlo:<.4g}" +
                 " " * max(1, width - len(f"{xlo:.4g}") - len(f"{xhi:.4g}")) + f"{xhi:.4g}")
    lines.append(" " * (label_width + 2) + xlabel.center(width))
    legend = "  ".join(f"{glyphs[i % len(glyphs)]} {name}" for i, (name, _) in enumerate(points))
    lines.append(f"  y = {ylabel}" + ("  (log scale)" if logy else ""))
    lines.append("  " + legend)
    return "\n".join(lines) + "\n"


def table(headers: Sequence[str], rows: Sequence[Sequence[object]]) -> str:
    """A fixed-width table. Blank cells stay blank; nothing is invented."""
    cells = [[("" if c is None else str(c)) for c in row] for row in rows]
    widths = [len(h) for h in headers]
    for row in cells:
        for i, cell in enumerate(row):
            if i < len(widths):
                widths[i] = max(widths[i], len(cell))
    out = ["  ".join(h.rjust(widths[i]) for i, h in enumerate(headers))]
    out.append("  ".join("-" * w for w in widths))
    for row in cells:
        out.append("  ".join(cell.rjust(widths[i]) for i, cell in enumerate(row)))
    return "\n".join(out) + "\n"


def fmt(value: float, digits: int = 1) -> str:
    if value is None or (isinstance(value, float) and not math.isfinite(value)):
        return "-"
    return f"{value:.{digits}f}"


# ------------------------------------------------------------------ optional PNG

def save_png(path: str, title: str, series: dict[str, Sequence[tuple[float, float]]],
             xlabel: str, ylabel: str, logy: bool = False) -> str | None:
    """Write a PNG if matplotlib is importable. Returns the path, or None.

    Never a hard dependency: the ASCII chart above is the deliverable.
    """
    try:
        import matplotlib
        matplotlib.use("Agg")
        import matplotlib.pyplot as plt
    except Exception:
        return None
    fig, ax = plt.subplots(figsize=(10, 5.5), dpi=130)
    for name, pts in series.items():
        pts = [(x, y) for x, y in pts if math.isfinite(y)]
        if not pts:
            continue
        ax.plot([p[0] for p in pts], [p[1] for p in pts], marker="o", markersize=3, label=name)
    ax.set_title(title)
    ax.set_xlabel(xlabel)
    ax.set_ylabel(ylabel)
    if logy:
        ax.set_yscale("log")
    ax.grid(True, alpha=0.3)
    ax.legend(fontsize=8)
    fig.tight_layout()
    fig.savefig(path)
    plt.close(fig)
    return path


def png_path(source: str, suffix: str) -> str:
    base = os.path.basename(source.rstrip("/")) or "out"
    base = base.replace(".csv.gz", "").replace(".csv", "")
    directory = source if os.path.isdir(source) else os.path.dirname(source) or "."
    return os.path.join(directory, f"{base}_{suffix}.png")


def note_png(path: str | None) -> str:
    if path:
        return f"\nWrote {path}\n"
    return ("\n(matplotlib not importable, so no PNG was written - the chart above is the\n"
            " deliverable. `python3 -m pip install matplotlib` if you want a file to paste.)\n")
