"""
Layer 5 lab - synthetic CSV fixtures, so the plotters run before k6 does.

WHAT THIS IS, AND WHAT IT IS NOT
  This writes k6-shaped CSV files into ../out/fixtures/ from a MODEL. Every
  number in them is generated by the arithmetic below - S/(1-rho), a retry
  multiplier, a token bucket, 1-(1-p)^K - seeded so two runs produce the same
  file.

  They exist for exactly one purpose: to exercise the plotting scripts when
  Docker and k6 are not available, so a broken plotter is found by running it
  rather than by reading it.

  THEY ARE NOT MEASUREMENTS. Nothing produced by this file belongs in a
  results table, a prediction table, or a sentence beginning "we observed".
  Every file it writes starts with a `# SYNTHETIC` comment line saying so, and
  every plotter prints a warning when it reads one. If you want numbers, run
  the stack.

  The model is also deliberately simple-minded: it has no metastability, no
  coordinated omission and no surprises in it. It cannot teach you anything,
  which is the point - if a chart drawn from these files looks interesting,
  the interest is in the plotter, not in the system.

RUN
    python3 tools/make_fixtures.py            # writes out/fixtures/*.csv
    python3 tools/plot_knee.py out/fixtures/ramp.csv
"""
from __future__ import annotations

import math
import os
import random
import time

HEADER = ("metric_name,timestamp,metric_value,check,error,error_code,expected_response,"
          "group,method,name,proto,scenario,service,status,subproto,tls_version,url,"
          "extra_tags,metadata")

BANNER = ("# SYNTHETIC - generated by tools/make_fixtures.py from a model, not measured.\n"
          "# Use it to check that a plotter works. Never as a result.\n")

OUT = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
                   "out", "fixtures")

START = 1_755_000_000.0     # a fixed epoch, so the files are byte-stable


class Writer:
    def __init__(self, name: str) -> None:
        self.path = os.path.join(OUT, name)
        self.rows: list[str] = []

    def add(self, metric: str, t: float, value: float, tags: dict,
            status: str = "200", url: str = "http://app:8000/work") -> None:
        extra = "&".join(f"{k}={v}" for k, v in sorted(tags.items()))
        self.rows.append(
            f"{metric},{t:.3f},{value:.4f},,,,true,,GET,{url},HTTP/1.1,"
            f"{tags.get('scenario', 'default')},,{status},,,{url},{extra},"
        )

    def write(self) -> None:
        os.makedirs(OUT, exist_ok=True)
        with open(self.path, "w") as handle:
            handle.write(BANNER)
            handle.write(HEADER + "\n")
            handle.write("\n".join(self.rows) + "\n")
        print(f"  {os.path.relpath(self.path)}  ({len(self.rows)} samples)")


def lognormal_ms(median_ms: float, tail_ratio: float, rng: random.Random) -> float:
    sigma = math.log(tail_ratio) / 2.3263478740408408
    return rng.lognormvariate(math.log(median_ms), sigma)


def ramp(name: str = "ramp.csv", pool_total: int = 15, service_ms: float = 400.0,
         step_s: int = 10) -> None:
    """Topic 1: latency from S/(1-rho), and a completion rate that plateaus.

    One sample per COMPLETION, which is what k6 emits, and completions are
    spaced at min(offered, capacity) - so the `achieved` column plateaus at
    capacity above rho=1 exactly as a real run's does. Service time here is
    deliberately 400ms rather than 40ms so the file stays small: capacity is
    then 37.5 rps and a 10-second step is a few hundred rows rather than
    a few thousand.
    """
    rng = random.Random(1)
    w = Writer(name)
    capacity = pool_total / (service_ms / 1000.0)
    t = START
    for rho in (0.2, 0.5, 0.8, 0.9, 0.95, 1.1):
        offered = round(rho * capacity)
        served = min(offered, capacity)
        tags = {"rho": f"{rho}", "offered_rps": str(offered), "pool": str(pool_total),
                "endpoint": "work", "scenario": f"rho_{str(rho).replace('.', '')}"}
        step_end = t + step_s
        backlog = 0.0
        while t < step_end:
            t += 1.0 / served
            if rho < 1.0:
                wait = service_ms * (rho / (1 - rho))
            else:
                backlog += (offered - served) / served
                wait = backlog / capacity * 1000.0
            latency = service_ms + wait * rng.lognormvariate(0, 0.35)
            w.add("http_req_duration", t, latency, tags)
            w.add("pool_wait_ms", t, max(0.0, latency - service_ms), tags)
            w.add("inflight", t, min(pool_total, offered * latency / 1000.0), tags)
        t += 5
    w.write()


def retry_storm() -> None:
    """Topic 3: amplification rises during the fault; how far it falls is the variant."""
    profiles = {
        # (peak amplification, amplification it settles at after the fault)
        "naive": (9.0, 4.2),
        "jitter": (8.2, 3.1),
        "budget": (2.4, 1.05),
        "edge_only": (3.6, 1.6),
    }
    for variant, (peak, settled) in profiles.items():
        rng = random.Random(hash(variant) % 1000)
        w = Writer(f"03_retry_storm_{variant}.csv")
        tags = {"variant": variant, "hop": "service_c", "scenario": "poller"}
        offered = 50.0
        for second in range(0, 300, 2):
            t = START + second
            if second < 60:
                amp = 1.0
            elif second < 80:
                amp = 1.0 + (peak - 1.0) * min(1.0, (second - 60) / 8.0)
            else:
                decay = math.exp(-(second - 80) / 45.0)
                amp = settled + (peak - settled) * decay
            amp *= rng.uniform(0.97, 1.03)
            w.add("amplification", t, amp, tags)
            w.add("leaf_received_rps", t, offered * amp, tags)
            w.add("goodput_rps", t, offered / max(1.0, amp), tags)
            w.add("retry_ratio", t, max(0.0, amp - 1.0), tags)
            status = "200" if amp < 1.5 else "503"
            w.add("http_req_duration", t, 45.0 * amp, {"variant": variant, "endpoint": "chain",
                                                       "scenario": "load"}, status=status)
        w.write()


def metastable() -> None:
    """Topic 4: the hit rate comes back and goodput does not."""
    rng = random.Random(4)
    w = Writer("metastable.csv")
    tags = {"escape": "none", "scenario": "poller"}
    offered = 225.0
    for second in range(0, 600, 2):
        t = START + second
        if second < 180:
            hit, goodput, throughput = 95.0, offered, offered
        else:
            since = second - 180
            hit = 95.0 - 92.0 * math.exp(-since / 60.0)          # cache refills
            goodput = 12.0 + 8.0 * math.exp(-since / 200.0)      # and stays down
            throughput = 260.0 - 30.0 * math.exp(-since / 120.0)  # work continues
        jitter = rng.uniform(0.98, 1.02)
        w.add("hit_rate_pct", t, hit * rng.uniform(0.99, 1.01), tags)
        # goodput <= throughput always: goodput is the SUBSET of throughput
        # that somebody was still waiting for, so a model where it can exceed
        # throughput is a model that would teach the wrong thing.
        w.add("throughput_rps", t, throughput * jitter, tags)
        w.add("goodput_rps", t, min(goodput, throughput) * jitter, tags)
        w.add("retry_ratio", t, 0.02 if second < 180 else 1.9, tags)
        w.add("pg_conns", t, 1.0 if second < 180 else 15.0, tags)
    w.write()


def shed() -> None:
    """Topic 5: p99 of ACCEPTED requests, and where the rejections land."""
    capacity = 375.0
    for mode in ("none", "static", "priority", "adaptive"):
        rng = random.Random(hash(mode) % 997)
        w = Writer(f"05_shed_{mode}.csv")
        t = START
        for rho in (0.2, 0.5, 0.8, 0.9, 1.0, 1.1, 1.3):
            offered = round(rho * capacity)
            for tier in (("0", "3") if mode == "priority" else ("0",)):
                share = 0.3 if (mode == "priority" and tier == "0") else (
                    0.7 if mode == "priority" else 1.0)
                tags = {"rho": f"{rho}", "offered_rps": str(offered), "mode": mode,
                        "tier": tier, "endpoint": "work", "scenario": f"rho_{rho}"}
                n = max(60, int(offered * share) // 4)
                # One sample per completion, spaced at the offered rate, so
                # the plotter's accepted-rps column is comparable to `offered`.
                for _ in range(n):
                    t += 1.0 / max(1.0, offered * share)
                    if mode == "none":
                        shed_p = 0.0
                    elif mode == "priority":
                        # tier 0 keeps the whole limit; tier 3 starts losing
                        # first, which is the entire point of a tier.
                        shed_p = max(0.0, rho - (1.15 if tier == "0" else 0.85)) * 2.0
                    else:
                        shed_p = max(0.0, rho - 1.0) * 2.2
                    if rng.random() < min(0.85, shed_p):
                        w.add("http_req_duration", t, rng.uniform(1.0, 6.0), tags, status="503")
                        continue
                    if mode == "none" and rho >= 1.0:
                        latency = 400.0 + 2200.0 * (rho - 1.0) * rng.uniform(0.6, 1.4)
                    else:
                        eff = min(0.97, rho if mode == "none" else min(rho, 0.9))
                        latency = 40.0 / (1 - eff) * rng.lognormvariate(0, 0.3)
                    w.add("http_req_duration", t, latency, tags, status="200")
        w.write()


def fanout() -> None:
    """Topic 6: e2e tail against K, and the closed-loop comparison.

    There is a deliberate SLOW WINDOW in the middle of every run here - one
    second where the backends are eight times slower. Without it the draws are
    independent and coordinated omission cannot appear at all: the effect is
    not about slow requests, it is about slow PERIODS, during which a
    closed-loop generator sends fewer requests and therefore records fewer of
    the latencies that made it slow.
    """
    duration = 8.0
    slow_from, slow_to, slow_factor = 3.0, 4.0, 8.0

    def draw(rng: random.Random, k: int, elapsed: float) -> float:
        factor = slow_factor if slow_from <= elapsed < slow_to else 1.0
        return max(lognormal_ms(10.0, 20.0, rng) for _ in range(k)) * factor

    for k in (1, 2, 5, 10, 20, 50):
        rng = random.Random(600 + k)
        w = Writer(f"06_fanout_k{k}_hedgeoff.csv")
        tags = {"k": str(k), "hedge": "off", "dist": "lognormal", "model": "open",
                "endpoint": "fanout", "scenario": "fanout"}
        # OPEN model: fixed spacing. The generator does not care how slow the
        # server is, so the slow window is sampled as heavily as any other.
        rate = 50.0
        for i in range(int(duration * rate)):
            elapsed = i / rate
            slowest = draw(rng, k, elapsed)
            w.add("http_req_duration", START + elapsed, slowest + 2.0, tags,
                  url="http://gateway:8000/fanout")
            w.add("slowest_backend_ms", START + elapsed, slowest, tags,
                  url="http://gateway:8000/fanout")
        w.write()

    rng = random.Random(710)
    w = Writer("06_fanout_k10_hedgeon.csv")
    tags = {"k": "10", "hedge": "on", "dist": "lognormal", "model": "open",
            "endpoint": "fanout", "scenario": "fanout"}
    rate = 50.0
    for i in range(int(duration * rate)):
        elapsed = i / rate
        factor = slow_factor if slow_from <= elapsed < slow_to else 1.0
        draws = [lognormal_ms(10.0, 20.0, rng) * factor for _ in range(10)]
        p95 = 26.0
        hedged = [min(d, p95 + lognormal_ms(10.0, 20.0, rng)) if d > p95 else d for d in draws]
        w.add("http_req_duration", START + elapsed, max(hedged) + 2.0, tags,
              url="http://gateway:8000/fanout")
        w.add("slowest_backend_ms", START + elapsed, max(hedged), tags,
              url="http://gateway:8000/fanout")
    w.write()

    # CLOSED model: a fixed number of VUs, each waiting for its own response.
    # During the slow window every VU is blocked, so the generator sends far
    # fewer requests exactly when the latencies are worst - and those missing
    # samples are the coordinated omission.
    rng = random.Random(720)
    w = Writer("06_closed_loop_k10.csv")
    tags = {"k": "10", "hedge": "off", "dist": "lognormal", "model": "closed",
            "endpoint": "fanout", "scenario": "closed"}
    vus = 3
    elapsed = 0.0
    while elapsed < duration:
        slowest = draw(rng, 10, elapsed)
        w.add("http_req_duration", START + elapsed, slowest + 2.0, tags,
              url="http://gateway:8000/fanout")
        elapsed += (slowest / 1000.0) / vus
    w.write()


def main() -> None:
    os.makedirs(OUT, exist_ok=True)
    print("Writing SYNTHETIC fixtures (a model, not a measurement) into out/fixtures/ ...")
    ramp()
    retry_storm()
    metastable()
    shed()
    fanout()
    readme = os.path.join(OUT, "README.md")
    with open(readme, "w") as handle:
        handle.write(
            "# Synthetic fixtures\n\n"
            "Everything in this directory was generated by `tools/make_fixtures.py`\n"
            "from a model. **None of it is a measurement.** It exists so the plotting\n"
            "scripts in `tools/` can be run and checked on a machine with no Docker\n"
            "and no k6, and for nothing else.\n\n"
            "Every file starts with a `# SYNTHETIC` line, and every plotter prints a\n"
            "warning when it reads one. Do not copy a number out of a chart drawn\n"
            "from these files into any results table.\n\n"
            "Regenerate them with:\n\n"
            "    python3 tools/make_fixtures.py\n\n"
            "Real output goes in `out/` itself, written by\n"
            "`docker compose run --rm k6 run /scripts/... --out csv=/out/...`.\n"
        )
    print(f"  {os.path.relpath(readme)}")
    print("\nThese are a model, not a measurement. Do not put them in a results table.")
    print(f"(generated {time.strftime('%Y-%m-%d')})")


if __name__ == "__main__":
    main()
